import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Particles from "react-tsparticles";

export default function Home() {
  const particlesInit = (main) => {
    console.log(main);

    // you can initialize the tsParticles instance (main) here, adding custom shapes or presets
  };
  const particlesLoaded = (container) => {
    console.log(container);
  };
  return (
    <div className={styles.container}>
      <Head>
        <title>hi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="">
        <div className="text-center mt-2">
          <p className="text-2xl">i just wanna say tank u so muchhh</p>
        </div>

        <div className="text-center mt-10">
          <Image
            src={"/photo_2022-02-14_17-29-55.jpg"}
            height={400}
            width={500}
          />
          <p className="text-2xl">mash mafi</p>
        </div>

        <div className="text-center mt-10">
          <Image
            src={"/photo_2022-02-14_17-27-35.jpg"}
            height={400}
            width={500}
          />
          <p className="text-2xl">mash porya</p>
        </div>

        <Particles
          className={styles.par}
          id="tsparticles"
          init={particlesInit}
          loaded={particlesLoaded}
          options={{
            background: {
              color: {
                value: "#0d47a1",
              },
            },

            fpsLimit: 120,
            interactivity: {
              events: {
                onClick: {
                  enable: true,
                  mode: "push",
                },
                onHover: {
                  enable: true,
                  mode: "repulse",
                },
                resize: true,
              },
              modes: {
                bubble: {
                  distance: 400,
                  duration: 2,
                  opacity: 0.8,
                  size: 40,
                },
                push: {
                  quantity: 4,
                },
                repulse: {
                  distance: 200,
                  duration: 0.4,
                },
              },
            },
            particles: {
              color: {
                value: "#ffffff",
              },
              links: {
                color: "#ffffff",
                distance: 150,
                enable: true,
                opacity: 0.5,
                width: 1,
              },
              collisions: {
                enable: true,
              },
              move: {
                direction: "none",
                enable: true,
                outMode: "bounce",
                random: false,
                speed: 6,
                straight: false,
              },
              number: {
                density: {
                  enable: true,
                  area: 800,
                },
                value: 80,
              },
              opacity: {
                value: 0.5,
              },
              shape: {
                type: "circle",
              },
              size: {
                random: true,
                value: 5,
              },
            },
            detectRetina: true,
          }}
        ></Particles>
      </main>
    </div>
  );
}
